# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5]
        java: [ '1.8' ]
    name: Build Flink - JDK${{ matrix.os }}/${{ matrix.java }}/${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: build-target
        key: build-target-${{ hashFiles('**/pom.xml') }}
        restore-keys:
          build-target
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/com
        key: ${{ matrix.java }}-maven-com-${{ hashFiles('**/pom.xml') }}
        restore-keys:
          ${{ matrix.java }}-maven-com-
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/org
        key: ${{ matrix.java }}-maven-org-${{ hashFiles('**/pom.xml') }}
        restore-keys:
          ${{ matrix.java }}-maven-org-
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/net
        key: ${{ matrix.java }}-maven-net-${{ hashFiles('**/pom.xml') }}
        restore-keys:
          ${{ matrix.java }}-maven-net-
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/io
        key: ${{ matrix.java }}-maven-io-${{ hashFiles('**/pom.xml') }}
        restore-keys:
          ${{ matrix.java }}-maven-io-
    - name: Build with Maven
      run: |
        export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g"
        export MAVEN_CLI_OPTS="--no-transfer-progress"
        mkdir -p ~/.m2
        mvn clean install -Dmaven.javadoc.skip=true -DskipTests
        rm -rf ~/.m2/repository/org/apache/flink
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd flink-python
        python -m pip install --upgrade pip
        pip install cython==0.28.1
    - name: build bdist wheel
      run: |
        python setup.py bdist_wheel
        ls -al dist/